spring.application.name=product-service

# Actuator configuration
management.endpoints.web.exposure.include=info
management.info.env.enabled=true

# Custom info configuration
info.app.name=Product Service
info.app.description=This is the product service of the e-commerce platform
info.app.version=1.0.0

